# Generated by Django 5.2.3 on 2025-06-30 02:27

import django.db.models.deletion
import skillhub.models.role
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default=skillhub.models.role.get_default_role, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillhub.role'),
        ),
    ]
